# Generated by Django 2.1.2 on 2019-02-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SendPromotionMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emails', models.CharField(help_text='Para enviar mais de um e-mail, separe os mesmos por ";"', max_length=3000, verbose_name='E-mail')),
                ('tried', models.BooleanField(default=False, verbose_name='Tentou enviar?')),
                ('sent', models.BooleanField(default=False, verbose_name='Enviado?')),
            ],
            options={
                'verbose_name': 'uma tentiva de envio de e-mail',
                'verbose_name_plural': 'Enviar e-mails de divulgação',
                'ordering': ['-sent', 'emails'],
            },
        ),
    ]
