# Generated by Django 3.0 on 2021-01-03 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsPage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='photo',
            field=models.ImageField(upload_to='', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='project',
            name='small_photo',
            field=models.ImageField(blank=True, help_text='Caso nenhuma img seja selecionada, o sistema irá gerar uma miniatura automaticamente.', null=True, upload_to='', verbose_name='Foto Pequena'),
        ),
        migrations.AlterField(
            model_name='project',
            name='space',
            field=models.CharField(blank=True, choices=[('living room', 'Sala'), ('bedroom', 'Quarto'), ('home office', 'Escritório'), ('bathroom', 'Banheiro'), ('kitchen', 'Cozinha'), ('outside', 'Externa'), ('frontage', 'Fachada'), ('restaurant', 'Restaurante'), ('corporate', 'Corporativo'), ('tcc', 'TCC'), ('360', '360')], max_length=15, verbose_name='Ambiente'),
        ),
    ]
