# Generated by Django 3.0 on 2021-01-04 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsPage', '0002_auto_20210102_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='space',
            field=models.CharField(blank=True, choices=[('living room', 'Sala'), ('bedroom', 'Quarto'), ('home office', 'Escritório'), ('bathroom', 'Banheiro'), ('kitchen', 'Cozinha'), ('outside', 'Externa'), ('frontage', 'Fachada'), ('restaurant', 'Restaurante'), ('corporate', 'Corporativo / Comercial'), ('tcc', 'TCC'), ('360', '360')], max_length=15, verbose_name='Ambiente'),
        ),
    ]
